### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by tomaszmakarewicz** [tomaszmakarewicz/Dynamics#63]
When all issues are done for 2.0 milestone, we can start preparing release. In order to do so we need to do:
* <strike>Update manual</strike>
* <strike>Export it to Readme</strike>
* <strike>Tag release</strike>
* <strike>Put it to PPA: https://launchpad.net/~tomaszm/+archive/dynamics (don't forget about #47 )</strike>
* <strike>Update GitHub Wiki: https://github.com/tomaszmakarewicz/Dynamics/wiki</strike>
* <strike>Update PyMOL Wiki: http://www.pymolwiki.org/index.php/GROMACS_Plugin</strike>
* <strike>Inform Linux packagers about the release<strike>

**Comment by Xoden** [comment]
Your plugin is quite useful. Any plans on updating it to GROMACS 5?

**Comment by tomaszmakarewicz** [comment]
Hi,
I was busy with other projects, but I will be back here soon. Of course Gromacs 5.0 support is important and I have put this demand here: #66 .

**Comment by tomaszmakarewicz** [comment]
Done. 2.0 is now finally released!
