### ISSUE TITLE
gmx_mpi not detected

### ISSUE THREAD

**Issue by hackerzone85** [tomaszmakarewicz/Dynamics#74]
I have installed Gromacs 5.1.1in /usr/local/gromacs{bin, lib, include, share} dir and gmx_mpi is in path.
When i try to load Dynamics plugin from pymol it give the following error.
```bash
Error: 1
<type 'exceptions.ValueError'> Exception in Tk callback
  Function: <function init_function at 0x7fef494a12a8> (type: <type 'function'>)
  Args: ()
Traceback (innermost last):
  File "/usr/lib/python2.7/dist-packages/Pmw/Pmw_1_3/lib/PmwBase.py", line 1747, in __call__
    return apply(self.func, args)
  File "/usr/lib/python2.7/dist-packages/pmg_tk/startup/pymol_plugin_dynamics.py", line 1020, in init_function
    raise ValueError(status[1])
<type 'exceptions.ValueError'>: GROMACS not detected. Please install and setup GROMACS correctly for your platform. Aborting.
```

**Comment by tomaszmakarewicz** [comment]
Plugin use "gmx" binary to handle GROMACS. In case, where "gmx_mpi" binary is generated, plugin can not detect GROMACS.
The quick solution is just link gmx_mpi to gmx.
It can be also solved in the plugin, but require a little work.
