### ISSUE TITLE
Plugin not working as normal user

### ISSUE THREAD

**Issue by pratik-narain** [tomaszmakarewicz/Dynamics#77]
I compiled gromacs 5.1.3 on arch linux with mpi support and then installed pymol and this plugin as instructed in the guide. Now when I run pymol I can open the plugin only as root user. When I try to open it as normal user, it says GROMACS not detected. I tried linking gmx_mpi to gmx as suggested in an earlier post and also installing the plugin as a normal (non-root) user but nothing works. Any help is appreciated.

**Comment by tomaszmakarewicz** [comment]
Hi,
Can you run "gmx" command from the console as a normal user?

**Comment by pratik-narain** [comment]
yes. In fact I can run a whole MD simulation in gromacs from command line.

**Comment by tomaszmakarewicz** [comment]
The plugin should create ".dynamics" directory in your home directory. Please remove it to have clean environment. Then start PyMOL and the plugin again. If the error happens again, please attach "test_gromacs.txt" file which will appear in "~/.dynamics" directory.

**Comment by pratik-narain** [comment]
tried it. i am attaching the file
[test_gromacs.txt](https://github.com/tomaszmakarewicz/Dynamics/files/407006/test_gromacs.txt)
![image](https://cloud.githubusercontent.com/assets/20821855/17483289/10f8c0f2-5da3-11e6-9c1f-c42a0d4050fd.png)


Also attached is a screenshot to show that gmx is there in the path

**Comment by pratik-narain** [comment]
Solved it. I just realised that I need to link gmx_mpi as gmx somewhere in PATH. So, I did it in /usr/bin and now I think its working.
