### ISSUE TITLE
MD run with interchain disulfide bond

### ISSUE THREAD

**Issue by clinntt** [tomaszmakarewicz/Dynamics#78]
Hello,

I have tried in a number of ways to run a simulation of two peptides that are bridged with a disulfide bond, but in all cases the plugin breaks the disulfide (forming two cysteines) resulting in the two peptides diffusing away from each other.  Even in restrained MD runs, where I have selected the two sulfur atoms as the restraint, the peptides diffuse away.  Is there something wrong with my PDB file (attached below)?

Thanks!

Clint
Postdoctoral Fellow
University of Michigan

[tethered_peptides.txt](https://github.com/tomaszmakarewicz/Dynamics/files/629290/tethered_peptides.txt)

**Comment by tomaszmakarewicz** [comment]
Hi Clint,
Please ask GROMACS community how to correctly set up your simulation. After you acquire such a knowledge, you can then use the plugin to implement it.
