### ISSUE TITLE
Work with Gromacs 2016.1?

### ISSUE THREAD

**Issue by rjrich** [tomaszmakarewicz/Dynamics#79]
When I tried to run the plugin, I got the error message shown below. Is this because I need to configure it for Gromacs 2016.1? Will it run with this version of Gromacs?

Thank you.

=====

Error: 1
<type 'exceptions.IndexError'> Exception in Tk callback
  Function: <function init_function at 0x7fe746548398> (type: <type 'function'>)
  Args: ()
Traceback (innermost last):
  File "/home/rjrich/pymol/modules/Pmw/Pmw_1_2/lib/PmwBase.py", line 1747, in __call__
    return apply(self.func, args)
  File "/home/rjrich/pymol/modules/pmg_tk/startup/pymol_plugin_dynamics.py", line 1007, in init_function
    gromacs = Gromacs_output()
  File "/home/rjrich/pymol/modules/pmg_tk/startup/pymol_plugin_dynamics.py", line 63, in __init__
    gromacs_version = "GROMACS VERSION " + version[1]
<type 'exceptions.IndexError'>: list index out of range

=====

**Comment by tomaszmakarewicz** [comment]
GROMACS 2016.1 was not tested for this plugin, so problems may occur.

Could you please provide the content of ~/.dynamics/test_gromacs.txt ?

**Comment by tomaszmakarewicz** [comment]
New way of detecting GROMACS is now implemented in 2.0 branch and master branch.
As a result master branch of the plugin should work with GROMACS 2016.x releases as long, as they do not break API.
