### ISSUE TITLE
'nstxout' error in GROMACS when changing simulation time

### ISSUE THREAD

**Issue by mtrellet** [tomaszmakarewicz/Dynamics#81]
Hello Tomas,

Just bumped into this error recently when I tried to change the simulation time from the main window. When I edit the time (bottom right box) and click on `OK`, I can see that the _nstxout_ parameter get the value in the `Configure` window of _Molecular Dynamics Simulation_ (middle right button). However _nstxout_ is the

> number of steps that elapse between writing coordinates to output trajectory file, the last coordinates are always written

 It should not be directly impacted or directly impact the simulation time. By default it is at **20** and everything is ok.

Just for the record, the error appears when I start the simulation, I got a pop-up window reporting an error:

```
Fatal error:
There was 1 error in input file(s)
For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors
```

By looking at the log file (.dynamics/project_name/log.txt), I can find the following lines:

```
ERROR 1 [file md.mdp, line 39]:
  Right hand side '10.0' for parameter 'nstxout' in parameter file is not
  an integer value
```

That what lead me to the assumption that this parameter was not properly setup. And the only thing I did before running the simulation was to "confirm" the simulation time.

**Comment by tomaszmakarewicz** [comment]
Dear mtrellet,
Thank you for your bug report. Indeed, the plugin was changing bad md.mdp parameter. The proper one should be "nsteps". This is now fixed in master branch and 2.0 branch.
Best regards,
